export const CREATE_LIST_REQUEST = "CREATE_LIST_REQUEST"
export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS"
export const CREATE_LIST_FAILURE = "CREATE_LIST_FAILURE"

export const GET_LIST_REQUEST = "CREATE_LIST_REQUEST"
export const GET_LIST_SUCCESS = "CREATE_LIST_SUCCESS"
export const GET_LIST_FAILURE = "CREATE_LIST_FAILURE"