export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";

export const GET_TASK_REQUEST = "GET_TASK_REQUEST";
export const GET_TODAY_TASK_SUCCESS = "GET_TODAY_TASK_SUCCESS";
export const GET_TODAY_PENDING_TASK_SUCCESS = "GET_TODAY_PENDING_TASK_SUCCESS";
export const GET_TOMORROW_TASK_SUCCESS = "GET_TOMORROW_TASK_SUCCESS";
export const GET_WEEK_TASK_SUCCESS = "GET_WEEK_TASK_SUCCESS";
export const GET_TASK_FAILURE = "GET_TASK_FAILURE";

export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";

export const DELETE_MANY_TASK_REQUEST = "DELETE_MANY_TASK_REQUEST";
export const DELETE_MANY_TASK_SUCCESS = "DELETE_MANY_TASK_SUCCESS";
export const DELETE_MANY_TASK_FAILURE = "DELETE_MANY_TASK_FAILURE";