export const CREATE_STICKY_WALL_REQUEST = "CREATE_STICKY_WALL_REQUEST"
export const CREATE_STICKY_WALL_SUCCESS = "CREATE_STICKY_WALL_SUCCESS"
export const CREATE_STICKY_WALL_FAILURE = "CREATE_STICKY_WALL_FAILURE"

export const GET_STICKY_WALL_REQUEST = "GET_STICKY_WALL_REQUEST"
export const GET_STICKY_WALL_SUCCESS = "GET_STICKY_WALL_SUCCESS"
export const GET_STICKY_WALL_FAILURE = "GET_STICKY_WALL_FAILURE"
 