export const CREATE_TAG_REQUEST = "CREATE_TAG_REQUEST";
export const CREATE_TAG_SUCCESS = "CREATE_TAG_SUCCESS";
export const CREATE_TAG_FAILURE = "CREATE_TAG_FAILURE";

export const GET_TAG_REQUEST = "CREATE_TAG_REQUEST";
export const GET_TAG_SUCCESS = "CREATE_TAG_SUCCESS";
export const GET_TAG_FAILURE = "CREATE_TAG_FAILURE";